/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Upload limits for clients
     * @description The upload size limit and accepted file extensions, so a client can check a file before sending it.
     */
    get: operations['client_config_api_config_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/files/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List uploaded files */
    get: operations['list_files_api_files__get']
    put?: never
    /**
     * Upload a geospatial file
     * @description Validates the upload synchronously, then reads and measures it in the background.
     *
     *     A plain ``def`` on purpose: FastAPI runs it in a worker thread, so the blocking disk and
     *     database I/O below never stalls the event loop.
     *
     *     Returns **202 Accepted** with `status: PENDING`. Poll `GET /api/files/{id}` until
     *     `COMPLETED` (or `FAILED`, with the reason in `error`).
     */
    post: operations['upload_file_api_files__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/files/{file_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** File information and status */
    get: operations['get_file_api_files__file_id__get']
    put?: never
    post?: never
    /** Delete a file */
    delete: operations['delete_file_api_files__file_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/files/{file_id}/features/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Extracted features
     * @description Every feature with its index, geometry type, geometry (source CRS), CRS and properties.
     */
    get: operations['list_features_api_files__file_id__features__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/files/{file_id}/geojson/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Export as GeoJSON (EPSG:4326) with measurements
     * @description RFC 7946 FeatureCollection. Drop it into geojson.io or QGIS to see features with their measurements.
     */
    get: operations['export_geojson_api_files__file_id__geojson__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/files/{file_id}/measurements/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Feature measurements
     * @description Area (polygons) and length (lines) per feature, plus file-wide totals.
     *
     *     The summary always covers the whole file, independent of pagination and filters.
     */
    get: operations['list_measurements_api_files__file_id__measurements__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Liveness check
     * @description Is the process up? Never touches the database: Render polls this, and a database query on every poll
     *     would keep Neon's compute awake (it scales to zero when idle).
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Readiness check (database)
     * @description Runs `SELECT 1` against the database with a 5 s limit. Wakes Neon's compute if it is suspended.
     */
    get: operations['ready_health_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Body_upload_file_api_files__post */
    Body_upload_file_api_files__post: {
      /**
       * File
       * @description A .zip containing a Shapefile, or a .kml / .kmz file.
       */
      file: string
    }
    /** ClientConfig */
    ClientConfig: {
      /**
       * Accepted Extensions
       * @description File extensions the upload endpoint accepts.
       */
      accepted_extensions: string[]
      /**
       * Max Upload Mb
       * @description Largest accepted upload, in MB (1 MB = 1,048,576 bytes).
       */
      max_upload_mb: number
    }
    /** ErrorResponse */
    ErrorResponse: {
      /** Detail */
      detail: string
    }
    /** FeatureList */
    FeatureList: {
      /** File Id */
      file_id: string
      /** Items */
      items: components['schemas']['FeatureOut'][]
      /** Limit */
      limit: number
      /** Offset */
      offset: number
      /** Total */
      total: number
    }
    /** FeatureOut */
    FeatureOut: {
      /** Crs */
      crs: string | null
      /**
       * Feature Id
       * @description 0-based index of the feature in the file.
       */
      feature_id: number
      /**
       * Geometry
       * @description GeoJSON geometry in the file's own CRS.
       */
      geometry: {
        [key: string]: unknown
      } | null
      /** Geometry Type */
      geometry_type: string | null
      /** Layer */
      layer: string | null
      /** Properties */
      properties: {
        [key: string]: unknown
      }
    }
    /** FileInfo */
    FileInfo: {
      /**
       * Bbox
       * @description [min_lon, min_lat, max_lon, max_lat] in EPSG:4326; null until processed or if empty.
       */
      bbox?: number[] | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Crs
       * @description Source CRS of the file; 'MIXED' if layers differ.
       */
      crs: string | null
      /**
       * Error
       * @description Why processing failed (status FAILED only).
       */
      error?: string | null
      /** Feature Count */
      feature_count: number | null
      file_type: components['schemas']['FileType']
      /** Filename */
      filename: string
      /**
       * Geometry Types
       * @description Feature count per geometry type.
       */
      geometry_types?: {
        [key: string]: number
      }
      /** Id */
      id: string
      /** Links */
      links?: {
        [key: string]: string
      }
      /** Processed At */
      processed_at: string | null
      /** Size Bytes */
      size_bytes: number
      status: components['schemas']['FileStatus']
      /**
       * Total Area M2
       * @description Sum of the features' areas in m²; null until the file is COMPLETED.
       */
      total_area_m2?: number | null
      /**
       * Total Length M
       * @description Sum of the features' lengths in m; null until the file is COMPLETED.
       */
      total_length_m?: number | null
      /** Warnings */
      warnings?: string[]
    }
    /** FileList */
    FileList: {
      /** Items */
      items: components['schemas']['FileInfo'][]
      /** Limit */
      limit: number
      /** Offset */
      offset: number
      /** Total */
      total: number
    }
    /**
     * FileStatus
     * @enum {string}
     */
    FileStatus: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED'
    /**
     * FileType
     * @enum {string}
     */
    FileType: 'SHAPEFILE' | 'KML' | 'KMZ'
    /** GeodesicCheck */
    GeodesicCheck: {
      /** Area M2 */
      area_m2?: number | null
      /** Length M */
      length_m?: number | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** Health */
    Health: {
      /**
       * Status
       * @constant
       */
      status: 'ok'
      /** Version */
      version: string
    }
    /** MeasurementList */
    MeasurementList: {
      /** Crs */
      crs: string | null
      /** File Id */
      file_id: string
      /** Items */
      items: components['schemas']['MeasurementOut'][]
      /** Limit */
      limit: number
      /** Offset */
      offset: number
      summary: components['schemas']['MeasurementSummary']
      /** Total */
      total: number
      /**
       * Units
       * @default {
       *       "area": "square metres (m²)",
       *       "length": "metres (m)"
       *     }
       */
      units: {
        [key: string]: string
      }
    }
    /** MeasurementOut */
    MeasurementOut: {
      /** Area Hectares */
      area_hectares?: number | null
      /** Area M2 */
      area_m2?: number | null
      /** Feature Id */
      feature_id: number
      /** @description Independent ellipsoidal (WGS84) measurement used as a cross-check. */
      geodesic?: components['schemas']['GeodesicCheck'] | null
      /** Geometry Type */
      geometry_type: string | null
      /** Layer */
      layer: string | null
      /** Length Km */
      length_km?: number | null
      /** Length M */
      length_m?: number | null
      /**
       * Measurement Crs
       * @description Projected CRS the measurement was computed in.
       */
      measurement_crs: string | null
      /** Messages */
      messages?: string[]
      /** Perimeter M */
      perimeter_m?: number | null
      status: components['schemas']['MeasurementStatus']
    }
    /**
     * MeasurementStatus
     * @enum {string}
     */
    MeasurementStatus: 'MEASURED' | 'NOT_APPLICABLE' | 'UNSUPPORTED' | 'FAILED'
    /** MeasurementSummary */
    MeasurementSummary: {
      /** By Status */
      by_status: {
        [key: string]: number
      }
      /** Total Area Hectares */
      total_area_hectares: number
      /** Total Area M2 */
      total_area_m2: number
      /** Total Length Km */
      total_length_km: number
      /** Total Length M */
      total_length_m: number
    }
    /** Readiness */
    Readiness: {
      /**
       * Database
       * @enum {string}
       */
      database: 'ok' | 'unavailable'
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'unavailable'
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  client_config_api_config_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ClientConfig']
        }
      }
    }
  }
  list_files_api_files__get: {
    parameters: {
      query?: {
        status?: components['schemas']['FileStatus'] | null
        /** @description Page size. */
        limit?: number
        /** @description Number of items to skip. */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileList']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upload_file_api_files__post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_file_api_files__post']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileInfo']
        }
      }
      /** @description File too large. */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unsupported file type. */
      415: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description File is corrupt or incomplete. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_file_api_files__file_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        file_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileInfo']
        }
      }
      /** @description File not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description File not processed yet, or processing failed. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_file_api_files__file_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        file_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description File not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description File not processed yet, or processing failed. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_features_api_files__file_id__features__get: {
    parameters: {
      query?: {
        /** @description Filter, e.g. Polygon. */
        geometry_type?: string | null
        /** @description Page size. */
        limit?: number
        /** @description Number of items to skip. */
        offset?: number
      }
      header?: never
      path: {
        file_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FeatureList']
        }
      }
      /** @description File not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description File not processed yet, or processing failed. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  export_geojson_api_files__file_id__geojson__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        file_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description File not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description File not processed yet, or processing failed. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_measurements_api_files__file_id__measurements__get: {
    parameters: {
      query?: {
        status?: components['schemas']['MeasurementStatus'] | null
        /** @description Page size. */
        limit?: number
        /** @description Number of items to skip. */
        offset?: number
      }
      header?: never
      path: {
        file_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeasurementList']
        }
      }
      /** @description File not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description File not processed yet, or processing failed. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
    }
  }
  ready_health_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Readiness']
        }
      }
      /** @description Database unavailable or too slow (> 5 s). */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Readiness']
        }
      }
    }
  }
}
